platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'VH URL-Shortener' do
  
  use_frameworks!

  # Network handling and data request

end

# Diable cocoapod stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
