# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Vivus Test Url Shotener' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vivus Test Url Shotener
  pod 'VHUrlShortener', :path => '/Users/seunoboite/Documents/VivusHub/Url-Shortener/iOS/'

end
